language: go
go:
  - 1.10.x
  - 1.11.x
install:
  - go get github.com/skwair/discord
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.2
script:
  - golangci-lint run
  - go test -v -race ./...
