language: go
go:
  - 1.11.x
install:
  - go get github.com/skwair/harmony
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.13.1
script:
  - golangci-lint run
  - bash _scripts/build_examples.sh
  - go test -v -race ./...
