language: go
go:
  - 1.14.x
install:
  - go get github.com/skwair/harmony
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.27.0
script:
  - golangci-lint run --enable goimports
  - bash _scripts/build_examples.sh
